---
title: "Lab 7 Assignment: Group 13"
format:
  html:
    embed-resources: true
editor: visual
author: Thomas (s204540) Jakob (s194527) Mikkel (s193518) Jonathan (s184243) El Mehdi (s194533)
---

## **Load Libraries and set seed**

```{r}
library('tidyverse') 
library('ggrepel')
library('broom')
set.seed(420)
```

### **Load Data**

Download data from url if not already download, if in such case just load the file.

```{r}
data_dir <- "data/"
raw_dir <- "data/_raw/" 
data_file <- "gravier.RData" 
data_loc <- "https://github.com/ramhiser/datamicroarray/raw/master/data/"  

if ( !dir.exists(data_dir) ){
  dir.create(path = data_dir)
}

if( !dir.exists(raw_dir) ){
  dir.create(path = raw_dir) 
  } 

if( !file.exists(str_c(raw_dir, data_file)) ){   
  download.file(    
    url = str_c(data_loc, data_file),
    destfile = str_c(raw_dir, data_file))
  } 

load(file = str_c(raw_dir, data_file))
```

### **Data clean**

Clean data and save in gz compress version

```{r}
gravier_clean <- gravier |>
  bind_cols() |>
  as_tibble() 

write_csv(gravier_clean,"./data/02_gravier_clean.csv.gz")
```

### **data wrangling**

```{r}
gravier_clean_aug <- gravier_clean |>
  mutate(y = case_when(y == "poor" ~ 1,
                       y == "good" ~ 0)) |>
  relocate(early_metastasis = y)  

gravier_clean_aug_long <- gravier_clean_aug |>
  pivot_longer(     
    cols = !early_metastasis,
    names_to = "gene",
    values_to = "log2_expr_level"
    )  

sub_gravier <- gravier_clean_aug_long |>
  group_by(gene) |> 
  nest() |>
  ungroup()  

sub_gravier <- sub_gravier |>
  sample_n(size = 100)  

sub_gravier <- sub_gravier |>  
  group_by(gene) |> 
  mutate(model_object = map(
    .x = data,
    .f = ~lm(
      formula = log2_expr_level ~ early_metastasis,
      data = .x     
      ))) |>    
  mutate(model_object_tidy = map(     
    .x=model_object,     
    .f = ~tidy(       
      x = .x,       
      conf.int = TRUE,
      conf.level = 0.95
      )   
    ))  

gravier_estimates <- sub_gravier |>
  unnest(model_object_tidy)|>
  filter(term == "early_metastasis")

gravier_estimates <- gravier_estimates |>
  select(c(
    gene,
    p.value,
    estimate,
    conf.low,
    conf.high)) |>
  ungroup()

gravier_estimates <- gravier_estimates |> 
  mutate(q.value = map(     
    .x = p.value,     
    .f = ~p.adjust(.x)   
    )) |>    
  unnest(q.value) |> 
  mutate(is_significant = case_when(
    p.value > 0.05 ~ "no",
    p.value < 0.05 ~ "yes"
    ))
```
